export type DatabaseMigration = {
  id: string;
  description: string;
  sql: string;
};

export const TERRITORIAL_SECTORS_AND_PIURA_GEOGRAPHY_MIGRATION: DatabaseMigration = {
  id: "001-territorial-sectors-and-piura-geography",
  description:
    "Rebuilds test visit data, models territorial sectors and seeds Piura geography.",
  sql: `
    DELETE FROM visitas_campo;
    DELETE FROM parcelas;
    DELETE FROM sectores;

    CREATE TABLE IF NOT EXISTS departamentos (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      codigo varchar(2) NOT NULL UNIQUE,
      nombre varchar(100) NOT NULL UNIQUE
    );

    CREATE TABLE IF NOT EXISTS provincias (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      departamento_id bigint NOT NULL REFERENCES departamentos(id) ON DELETE RESTRICT,
      codigo varchar(4) NOT NULL UNIQUE,
      nombre varchar(100) NOT NULL,
      UNIQUE (departamento_id, nombre)
    );

    CREATE TABLE IF NOT EXISTS distritos (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      provincia_id bigint NOT NULL REFERENCES provincias(id) ON DELETE RESTRICT,
      ubigeo varchar(6) NOT NULL UNIQUE,
      nombre varchar(120) NOT NULL,
      UNIQUE (provincia_id, nombre)
    );

    INSERT INTO departamentos (codigo, nombre)
    VALUES ('20', 'Piura')
    ON CONFLICT (codigo) DO UPDATE SET nombre = EXCLUDED.nombre;

    INSERT INTO provincias (departamento_id, codigo, nombre)
    SELECT departamento.id, seed.codigo, seed.nombre
    FROM departamentos departamento
    CROSS JOIN (VALUES
      ('2001', 'Piura'),
      ('2002', 'Ayabaca'),
      ('2003', 'Huancabamba'),
      ('2004', 'Morropon'),
      ('2005', 'Paita'),
      ('2006', 'Sullana'),
      ('2007', 'Talara'),
      ('2008', 'Sechura')
    ) AS seed(codigo, nombre)
    WHERE departamento.codigo = '20'
    ON CONFLICT (codigo) DO UPDATE SET nombre = EXCLUDED.nombre;

    INSERT INTO distritos (provincia_id, ubigeo, nombre)
    SELECT provincia.id, seed.ubigeo, seed.nombre
    FROM provincias provincia
    JOIN (VALUES
      ('2001', '200101', 'Piura'),
      ('2001', '200104', 'Castilla'),
      ('2001', '200105', 'Catacaos'),
      ('2001', '200107', 'Cura Mori'),
      ('2001', '200108', 'El Tallan'),
      ('2001', '200109', 'La Arena'),
      ('2001', '200110', 'La Union'),
      ('2001', '200111', 'Las Lomas'),
      ('2001', '200114', 'Tambogrande'),
      ('2001', '200115', 'Veintiseis de Octubre'),
      ('2002', '200201', 'Ayabaca'),
      ('2002', '200202', 'Frias'),
      ('2002', '200203', 'Jilili'),
      ('2002', '200204', 'Lagunas'),
      ('2002', '200205', 'Montero'),
      ('2002', '200206', 'Pacaipampa'),
      ('2002', '200207', 'Paimas'),
      ('2002', '200208', 'Sapillica'),
      ('2002', '200209', 'Sicchez'),
      ('2002', '200210', 'Suyo'),
      ('2003', '200301', 'Huancabamba'),
      ('2003', '200302', 'Canchaque'),
      ('2003', '200303', 'El Carmen de la Frontera'),
      ('2003', '200304', 'Huarmaca'),
      ('2003', '200305', 'Lalaquiz'),
      ('2003', '200306', 'San Miguel de El Faique'),
      ('2003', '200307', 'Sondor'),
      ('2003', '200308', 'Sondorillo'),
      ('2004', '200401', 'Chulucanas'),
      ('2004', '200402', 'Buenos Aires'),
      ('2004', '200403', 'Chalaco'),
      ('2004', '200404', 'La Matanza'),
      ('2004', '200405', 'Morropon'),
      ('2004', '200406', 'Salitral'),
      ('2004', '200407', 'San Juan de Bigote'),
      ('2004', '200408', 'Santa Catalina de Mossa'),
      ('2004', '200409', 'Santo Domingo'),
      ('2004', '200410', 'Yamango'),
      ('2005', '200501', 'Paita'),
      ('2005', '200502', 'Amotape'),
      ('2005', '200503', 'Arenal'),
      ('2005', '200504', 'Colan'),
      ('2005', '200505', 'La Huaca'),
      ('2005', '200506', 'Tamarindo'),
      ('2005', '200507', 'Vichayal'),
      ('2006', '200601', 'Sullana'),
      ('2006', '200602', 'Bellavista'),
      ('2006', '200603', 'Ignacio Escudero'),
      ('2006', '200604', 'Lancones'),
      ('2006', '200605', 'Marcavelica'),
      ('2006', '200606', 'Miguel Checa'),
      ('2006', '200607', 'Querecotillo'),
      ('2006', '200608', 'Salitral'),
      ('2007', '200701', 'Parinas'),
      ('2007', '200702', 'El Alto'),
      ('2007', '200703', 'La Brea'),
      ('2007', '200704', 'Lobitos'),
      ('2007', '200705', 'Los Organos'),
      ('2007', '200706', 'Mancora'),
      ('2008', '200801', 'Sechura'),
      ('2008', '200802', 'Bellavista de la Union'),
      ('2008', '200803', 'Bernal'),
      ('2008', '200804', 'Cristo Nos Valga'),
      ('2008', '200805', 'Vice'),
      ('2008', '200806', 'Rinconada Llicuar')
    ) AS seed(provincia_codigo, ubigeo, nombre)
      ON provincia.codigo = seed.provincia_codigo
    ON CONFLICT (ubigeo) DO UPDATE SET nombre = EXCLUDED.nombre;

    ALTER TABLE sectores DROP COLUMN IF EXISTS productor_id CASCADE;
    ALTER TABLE sectores ADD COLUMN IF NOT EXISTS distrito_id bigint;
    ALTER TABLE sectores ALTER COLUMN distrito_id SET NOT NULL;
    ALTER TABLE sectores
      ADD CONSTRAINT sectores_distrito_id_fkey
      FOREIGN KEY (distrito_id) REFERENCES distritos(id) ON DELETE RESTRICT;
    ALTER TABLE sectores
      ADD CONSTRAINT sectores_distrito_id_nombre_key UNIQUE (distrito_id, nombre);

    ALTER TABLE parcelas ADD COLUMN IF NOT EXISTS productor_id bigint;
    ALTER TABLE parcelas ALTER COLUMN productor_id SET NOT NULL;
    ALTER TABLE parcelas
      ADD CONSTRAINT parcelas_productor_id_fkey
      FOREIGN KEY (productor_id) REFERENCES productores(id) ON DELETE RESTRICT;
    ALTER TABLE parcelas DROP CONSTRAINT IF EXISTS parcelas_sector_id_codigo_key;
    ALTER TABLE parcelas
      ADD CONSTRAINT parcelas_productor_id_sector_id_codigo_key
      UNIQUE (productor_id, sector_id, codigo);

    CREATE INDEX IF NOT EXISTS idx_provincias_departamento_id
      ON provincias(departamento_id);
    CREATE INDEX IF NOT EXISTS idx_distritos_provincia_id
      ON distritos(provincia_id);
    CREATE INDEX IF NOT EXISTS idx_sectores_distrito_id
      ON sectores(distrito_id);
    CREATE INDEX IF NOT EXISTS idx_parcelas_productor_id
      ON parcelas(productor_id);
    CREATE INDEX IF NOT EXISTS idx_parcelas_productor_sector
      ON parcelas(productor_id, sector_id);
  `
};
