import type { DatabaseMigration } from "./001-territorial-sectors-and-piura-geography";

export const SUB_ETAPAS_MIGRATION: DatabaseMigration = {
  id: "003-sub-etapas",
  description: "Creates sub stages linked to phenological stages.",
  sql: `
    CREATE TABLE IF NOT EXISTS sub_etapas (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      etapa_fenologica_id bigint NOT NULL,
      nombre varchar(100) NOT NULL,
      orden integer NOT NULL,
      descripcion text,
      porcentaje numeric(5, 2),
      estado boolean NOT NULL DEFAULT true,
      CONSTRAINT sub_etapas_etapa_fenologica_id_fkey
        FOREIGN KEY (etapa_fenologica_id)
        REFERENCES etapas_fenologicas(id)
        ON DELETE RESTRICT,
      CONSTRAINT sub_etapas_etapa_orden_key
        UNIQUE (etapa_fenologica_id, orden),
      CONSTRAINT sub_etapas_etapa_nombre_key
        UNIQUE (etapa_fenologica_id, nombre),
      CONSTRAINT sub_etapas_porcentaje_check
        CHECK (porcentaje IS NULL OR (porcentaje >= 0 AND porcentaje <= 100))
    );

    CREATE INDEX IF NOT EXISTS idx_sub_etapas_etapa_fenologica_id
      ON sub_etapas(etapa_fenologica_id);

    CREATE INDEX IF NOT EXISTS idx_sub_etapas_estado
      ON sub_etapas(estado);
  `
};
