import type { DatabaseMigration } from "./001-territorial-sectors-and-piura-geography";

export const MODULO_CLIMA_TERRITORIAL_MIGRATION: DatabaseMigration = {
  id: "032-modulo-clima-territorial",
  description: "Creates the independent territorial climate module and its initial sources.",
  sql: `
    CREATE SCHEMA IF NOT EXISTS clima;
    CREATE TABLE IF NOT EXISTS clima.fuentes_datos (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      codigo varchar(40) NOT NULL UNIQUE, nombre varchar(120) NOT NULL,
      tipo varchar(30) NOT NULL, estado varchar(30) NOT NULL DEFAULT 'SIN_CONFIGURAR',
      ultima_consulta_exitosa_at timestamptz, ultimo_error text, respuesta_promedio_ms integer,
      activo boolean NOT NULL DEFAULT true, creado_at timestamptz NOT NULL DEFAULT now(), actualizado_at timestamptz NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS clima.puntos_climaticos (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
      nombre varchar(120) NOT NULL, departamento varchar(100) NOT NULL, distrito varchar(100) NOT NULL,
      latitud numeric(9,6) NOT NULL CHECK(latitud BETWEEN -90 AND 90), longitud numeric(9,6) NOT NULL CHECK(longitud BETWEEN -180 AND 180),
      activo boolean NOT NULL DEFAULT true, creado_at timestamptz NOT NULL DEFAULT now(), actualizado_at timestamptz NOT NULL DEFAULT now(),
      UNIQUE(departamento, distrito)
    );
    CREATE TABLE IF NOT EXISTS clima.estaciones_meteorologicas (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
      punto_climatico_id bigint REFERENCES clima.puntos_climaticos(id) ON DELETE SET NULL,
      nombre varchar(150) NOT NULL, codigo varchar(80), tipo varchar(30) NOT NULL, fuente_id bigint REFERENCES clima.fuentes_datos(id) ON DELETE SET NULL,
      latitud numeric(9,6) NOT NULL CHECK(latitud BETWEEN -90 AND 90), longitud numeric(9,6) NOT NULL CHECK(longitud BETWEEN -180 AND 180),
      altitud_m numeric(10,2), variables_json jsonb NOT NULL DEFAULT '[]'::jsonb, frecuencia_minutos integer,
      ultima_comunicacion_at timestamptz, estado varchar(30) NOT NULL DEFAULT 'SIN_CONFIGURAR', activo boolean NOT NULL DEFAULT true,
      creado_at timestamptz NOT NULL DEFAULT now(), actualizado_at timestamptz NOT NULL DEFAULT now(), UNIQUE(codigo)
    );
    CREATE TABLE IF NOT EXISTS clima.lecturas (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fuente_id bigint NOT NULL REFERENCES clima.fuentes_datos(id) ON DELETE RESTRICT,
      punto_climatico_id bigint REFERENCES clima.puntos_climaticos(id) ON DELETE CASCADE, estacion_id bigint REFERENCES clima.estaciones_meteorologicas(id) ON DELETE CASCADE,
      variable varchar(60) NOT NULL, valor numeric(14,4) NOT NULL, unidad varchar(20) NOT NULL, tipo varchar(20) NOT NULL,
      dato_at timestamptz NOT NULL, recibido_at timestamptz NOT NULL DEFAULT now(), calidad varchar(20) NOT NULL DEFAULT 'VALIDO', modelo varchar(80),
      CHECK(punto_climatico_id IS NOT NULL OR estacion_id IS NOT NULL)
    );
    CREATE TABLE IF NOT EXISTS clima.pronosticos (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fuente_id bigint NOT NULL REFERENCES clima.fuentes_datos(id) ON DELETE RESTRICT,
      punto_climatico_id bigint NOT NULL REFERENCES clima.puntos_climaticos(id) ON DELETE CASCADE,
      variable varchar(60) NOT NULL, valor numeric(14,4) NOT NULL, unidad varchar(20) NOT NULL,
      valido_at timestamptz NOT NULL, emitido_at timestamptz NOT NULL, recibido_at timestamptz NOT NULL DEFAULT now(), modelo varchar(80),
      UNIQUE(fuente_id, punto_climatico_id, variable, valido_at, emitido_at)
    );
    CREATE TABLE IF NOT EXISTS clima.umbrales_alerta (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, codigo varchar(60) NOT NULL UNIQUE, variable varchar(60) NOT NULL,
      operador varchar(4) NOT NULL CHECK(operador IN ('>=','<=')), valor_precaucion numeric(14,4), valor_alta numeric(14,4), valor_critica numeric(14,4), unidad varchar(20) NOT NULL,
      activo boolean NOT NULL DEFAULT true, creado_at timestamptz NOT NULL DEFAULT now(), actualizado_at timestamptz NOT NULL DEFAULT now()
    );
    CREATE TABLE IF NOT EXISTS clima.alertas (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
      umbral_id bigint REFERENCES clima.umbrales_alerta(id) ON DELETE SET NULL, punto_climatico_id bigint NOT NULL REFERENCES clima.puntos_climaticos(id) ON DELETE CASCADE,
      fuente_id bigint REFERENCES clima.fuentes_datos(id) ON DELETE SET NULL, severidad varchar(20) NOT NULL, estado varchar(20) NOT NULL DEFAULT 'ACTIVA',
      variable varchar(60) NOT NULL, valor numeric(14,4) NOT NULL, unidad varchar(20) NOT NULL, inicio_at timestamptz NOT NULL, fin_at timestamptz,
      creado_at timestamptz NOT NULL DEFAULT now(), atendido_at timestamptz, UNIQUE(umbral_id, punto_climatico_id, inicio_at)
    );
    CREATE TABLE IF NOT EXISTS clima.ejecuciones_sincronizacion (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, fuente_id bigint REFERENCES clima.fuentes_datos(id) ON DELETE SET NULL,
      tipo varchar(30) NOT NULL, inicio_at timestamptz NOT NULL DEFAULT now(), fin_at timestamptz, estado varchar(20) NOT NULL, detalle text
    );
    CREATE INDEX IF NOT EXISTS idx_clima_lecturas_punto_variable_fecha ON clima.lecturas(punto_climatico_id, variable, dato_at DESC);
    CREATE UNIQUE INDEX IF NOT EXISTS uq_clima_lecturas_origen_variable_fecha
      ON clima.lecturas(fuente_id, COALESCE(punto_climatico_id, -1), COALESCE(estacion_id, -1), variable, tipo, dato_at);
    CREATE INDEX IF NOT EXISTS idx_clima_pronosticos_punto_fecha ON clima.pronosticos(punto_climatico_id, valido_at);
    CREATE INDEX IF NOT EXISTS idx_clima_alertas_estado_punto ON clima.alertas(estado, punto_climatico_id, inicio_at DESC);
    INSERT INTO clima.fuentes_datos(codigo,nombre,tipo,estado,activo) VALUES
      ('open_meteo','Open-Meteo','MODELO','OPERATIVA',true),('nasa_power','NASA POWER','HISTORICO','OPERATIVA',true),('senamhi','SENAMHI','OFICIAL','SIN_CONFIGURAR',false)
    ON CONFLICT(codigo) DO UPDATE SET nombre=EXCLUDED.nombre, tipo=EXCLUDED.tipo;
    INSERT INTO clima.puntos_climaticos(nombre,departamento,distrito,latitud,longitud) VALUES
      ('Tambogrande','Piura','Tambogrande',-4.926000,-80.344000),('Las Lomas','Piura','Las Lomas',-4.653000,-80.246000),('Casma','Áncash','Casma',-9.474000,-78.307000),('Motupe','Lambayeque','Motupe',-6.151000,-79.714000)
    ON CONFLICT(departamento,distrito) DO UPDATE SET nombre=EXCLUDED.nombre,latitud=EXCLUDED.latitud,longitud=EXCLUDED.longitud,actualizado_at=now();
    INSERT INTO clima.umbrales_alerta(codigo,variable,operador,valor_precaucion,valor_alta,valor_critica,unidad) VALUES
      ('temperatura_alta','temperature_2m_max','>=',35,38,40,'°C'),('temperatura_baja','temperature_2m_min','<=',12,8,5,'°C'),('probabilidad_lluvia','precipitation_probability','>=',70,90,95,'%'),('lluvia_intensa','precipitation_sum','>=',25,50,75,'mm'),('viento_fuerte','wind_speed_10m_max','>=',35,50,65,'km/h'),('et0_alta','et0','>=',6,7.5,9,'mm')
    ON CONFLICT(codigo) DO NOTHING;
    -- Rollback operativo: deshabilitar módulo y tareas conservando auditoría. Para rollback físico, respaldar y ejecutar DROP SCHEMA clima CASCADE solo con autorización.
  `
};
