import type { DatabaseMigration } from "./001-territorial-sectors-and-piura-geography";

export const RESERVORIOS_ENTORNO_AGROCLIMATICO_MIGRATION: DatabaseMigration = {
  id: "044-reservorios-entorno-agroclimatico",
  description:
    "Crea reservorios, lecturas hídricas auditables y la fuente de carga manual.",
  sql: `
    CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_public_id
      ON usuarios(public_id);

    CREATE TABLE IF NOT EXISTS clima.reservorios (
      id bigint GENERATED BY DEFAULT AS IDENTITY,
      public_id uuid NOT NULL DEFAULT gen_random_uuid(),
      nombre varchar(120) NOT NULL,
      departamento varchar(60),
      provincia varchar(80),
      distrito varchar(80),
      latitud double precision NOT NULL,
      longitud double precision NOT NULL,
      capacidad_max_mmc double precision,
      cota_max_msnm double precision,
      creado_at timestamptz NOT NULL DEFAULT now(),
      actualizado_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT pk_clima_reservorios PRIMARY KEY (id),
      CONSTRAINT uq_clima_reservorios_public_id UNIQUE (public_id),
      CONSTRAINT uq_clima_reservorios_nombre_ubicacion
        UNIQUE (nombre, departamento, provincia, distrito),
      CONSTRAINT ck_clima_reservorios_latitud
        CHECK (latitud BETWEEN -90 AND 90),
      CONSTRAINT ck_clima_reservorios_longitud
        CHECK (longitud BETWEEN -180 AND 180),
      CONSTRAINT ck_clima_reservorios_capacidad
        CHECK (capacidad_max_mmc IS NULL OR capacidad_max_mmc > 0),
      CONSTRAINT ck_clima_reservorios_cota
        CHECK (cota_max_msnm IS NULL OR cota_max_msnm > 0)
    );

    CREATE TABLE IF NOT EXISTS clima.lecturas_reservorios (
      id bigint GENERATED BY DEFAULT AS IDENTITY,
      public_id uuid NOT NULL DEFAULT gen_random_uuid(),
      reservorio_id bigint NOT NULL,
      fuente_id bigint,
      variable varchar(60) NOT NULL,
      valor double precision NOT NULL,
      unidad varchar(20) NOT NULL,
      tipo varchar(30) NOT NULL DEFAULT 'OBSERVADO',
      dato_at timestamptz NOT NULL,
      creado_por uuid,
      recibido_at timestamptz NOT NULL DEFAULT now(),
      creado_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT pk_clima_lecturas_reservorios PRIMARY KEY (id),
      CONSTRAINT uq_clima_lecturas_reservorios_public_id UNIQUE (public_id),
      CONSTRAINT fk_clima_lecturas_reservorio
        FOREIGN KEY (reservorio_id)
        REFERENCES clima.reservorios(id)
        ON DELETE RESTRICT,
      CONSTRAINT fk_clima_lecturas_fuente
        FOREIGN KEY (fuente_id)
        REFERENCES clima.fuentes_datos(id)
        ON DELETE SET NULL,
      CONSTRAINT fk_clima_lecturas_creado_por
        FOREIGN KEY (creado_por)
        REFERENCES usuarios(public_id)
        ON DELETE SET NULL,
      CONSTRAINT ck_clima_lecturas_variable CHECK (
        variable IN (
          'cota_msnm',
          'volumen_mmc',
          'caudal_entrada_m3s',
          'caudal_salida_m3s',
          'evaporacion_mm'
        )
      ),
      CONSTRAINT ck_clima_lecturas_tipo
        CHECK (tipo IN ('OBSERVADO', 'ESTIMADO'))
    );

    CREATE INDEX IF NOT EXISTS idx_lecturas_reservorios_reservorio
      ON clima.lecturas_reservorios(reservorio_id, variable, dato_at DESC);

    INSERT INTO clima.fuentes_datos(codigo, nombre, tipo, estado, activo)
    VALUES ('manual_reservorios', 'Carga manual', 'MANUAL', 'OPERATIVA', true)
    ON CONFLICT (codigo) DO UPDATE
    SET nombre = EXCLUDED.nombre,
        tipo = EXCLUDED.tipo,
        estado = EXCLUDED.estado,
        activo = EXCLUDED.activo,
        actualizado_at = now();

    INSERT INTO clima.reservorios(
      nombre,
      departamento,
      provincia,
      distrito,
      latitud,
      longitud,
      capacidad_max_mmc,
      cota_max_msnm
    ) VALUES
      ('Poechos', 'Piura', 'Sullana', 'Lancones', -4.683333, -80.500000, 885, 108),
      ('San Lorenzo', 'Piura', 'Piura', 'Las Lomas', -4.675640, -80.199234, 200, 70)
    ON CONFLICT (nombre, departamento, provincia, distrito) DO UPDATE
    SET latitud = EXCLUDED.latitud,
        longitud = EXCLUDED.longitud,
        capacidad_max_mmc = EXCLUDED.capacidad_max_mmc,
        cota_max_msnm = EXCLUDED.cota_max_msnm,
        actualizado_at = now();

    -- Rollback operativo: primero retirar el código consumidor. Tras un backup
    -- validado, eliminar lecturas_reservorios antes de reservorios y borrar la
    -- fuente manual_reservorios solo si ninguna otra fila la referencia. El
    -- índice único de usuarios se conserva porque protege el identificador
    -- público usado por autenticación y por la auditoría de otras entidades.
  `
};
