import type { DatabaseMigration } from "./001-territorial-sectors-and-piura-geography";

export const INTEGRACION_DIARIA_WEATHERLINK_MIGRATION: DatabaseMigration = {
  id: "045-integracion-diaria-weatherlink",
  description: "Registra WeatherLink y el progreso diario por estacion.",
  sql: `
    CREATE TABLE IF NOT EXISTS clima.estaciones_estado_sincronizacion (
      id bigint GENERATED BY DEFAULT AS IDENTITY,
      public_id uuid NOT NULL DEFAULT gen_random_uuid(),
      fuente_id bigint NOT NULL,
      estacion_id bigint NOT NULL,
      estado varchar(30) NOT NULL DEFAULT 'PENDIENTE',
      ultimo_dia_completo date,
      ultimo_intento_at timestamptz,
      ultimo_exito_at timestamptz,
      detalle varchar(500),
      creado_at timestamptz NOT NULL DEFAULT now(),
      actualizado_at timestamptz NOT NULL DEFAULT now(),
      CONSTRAINT pk_clima_estaciones_estado_sync PRIMARY KEY (id),
      CONSTRAINT uq_clima_estaciones_estado_sync_public_id UNIQUE (public_id),
      CONSTRAINT uq_clima_estaciones_estado_sync_fuente_estacion
        UNIQUE (fuente_id, estacion_id),
      CONSTRAINT fk_clima_estaciones_estado_sync_fuente
        FOREIGN KEY (fuente_id) REFERENCES clima.fuentes_datos(id) ON DELETE RESTRICT,
      CONSTRAINT fk_clima_estaciones_estado_sync_estacion
        FOREIGN KEY (estacion_id) REFERENCES clima.estaciones_meteorologicas(id) ON DELETE CASCADE,
      CONSTRAINT ck_clima_estaciones_estado_sync_estado
        CHECK (estado IN ('PENDIENTE', 'SINCRONIZANDO', 'COMPLETADA', 'ERROR'))
    );

    CREATE INDEX IF NOT EXISTS idx_clima_estaciones_estado_sync_estado
      ON clima.estaciones_estado_sincronizacion(estado, actualizado_at DESC);

    INSERT INTO clima.fuentes_datos(codigo, nombre, tipo, estado, activo)
    VALUES ('weatherlink', 'WeatherLink Davis', 'ESTACION', 'SIN_CONFIGURAR', true)
    ON CONFLICT (codigo) DO UPDATE
    SET nombre = EXCLUDED.nombre,
        tipo = EXCLUDED.tipo,
        actualizado_at = now();

    -- Rollback operativo: WEATHERLINK_ENABLED=false y fuente inactiva. Conservar
    -- lecturas y progreso. Un rollback fisico requiere backup y retirar primero
    -- esta tabla; las observaciones importadas no se eliminan automaticamente.
  `
};
