import { TERRITORIAL_SECTORS_AND_PIURA_GEOGRAPHY_MIGRATION } from "./001-territorial-sectors-and-piura-geography";
import { ETAPAS_FENOLOGICAS_ORDER_AND_TYPE_MIGRATION } from "./002-etapas-fenologicas-order-and-type";

export const DATABASE_MIGRATIONS = [
  TERRITORIAL_SECTORS_AND_PIURA_GEOGRAPHY_MIGRATION,
  ETAPAS_FENOLOGICAS_ORDER_AND_TYPE_MIGRATION
] as const;
