import { TERRITORIAL_SECTORS_AND_PIURA_GEOGRAPHY_MIGRATION } from "./001-territorial-sectors-and-piura-geography";
import { ETAPAS_FENOLOGICAS_ORDER_AND_TYPE_MIGRATION } from "./002-etapas-fenologicas-order-and-type";
import { SUB_ETAPAS_MIGRATION } from "./003-sub-etapas";
import { VISITA_SUB_ETAPA_AND_AREA_MIGRATION } from "./004-visita-sub-etapa-and-area";
import { UPDATE_CUAJADO_SUB_ETAPAS_MIGRATION } from "./005-update-cuajado-sub-etapas";
import { PLAGAS_ENFERMEDADES_SCIENTIFIC_NAME_MIGRATION } from "./006-plagas-enfermedades-scientific-name";
import { NIVELES_INCIDENCIA_SEVERIDAD_MIGRATION } from "./007-niveles-incidencia-severidad";
import { PLAGAS_ENFERMEDADES_ETAPA_FENOLOGICA_MIGRATION } from "./008-plagas-enfermedades-etapa-fenologica";
import { PLAGAS_ENFERMEDADES_ETAPAS_NIVELES_MIGRATION } from "./009-plagas-enfermedades-etapas-niveles";
import { VISITA_SANITARY_SEVERITY_AND_STEP_NOTES_MIGRATION } from "./010-visita-sanitary-severity-and-step-notes";
import { NUTRIENTES_DETALLE_NUTRIENTES_MIGRATION } from "./011-nutrientes-detalle-nutrientes";
import { OPERATIONAL_CATALOGS_MIGRATION } from "./012-operational-catalogs";
import { VISITA_RIEGO_LABORES_MIGRATION } from "./013-visita-riego-labores";
import { VISITA_OBSERVACION_SANITARIA_ORGANOS_MIGRATION } from "./014-visita-observacion-sanitaria-organos";
import { UPDATE_VISITA_OBSERVACION_SANITARIA_ORGANOS_MIGRATION } from "./015-update-visita-observacion-sanitaria-organos";
import { UPDATE_VISITA_OBSERVACION_SANITARIA_ORGANOS_CURRENT_VALUES_MIGRATION } from "./016-update-visita-observacion-sanitaria-organos-current-values";
import { STANDARDIZE_STEP_FIVE_FIELD_WORK_CATALOG_MIGRATION } from "./017-standardize-step-five-field-work-catalog";
import { VISIT_INCIDENCE_AND_NUTRITION_ORGANS_MIGRATION } from "./018-visit-incidence-and-nutrition-organs";
import { VISITA_RECETAS_MIGRATION } from "./019-visita-recetas";
import { RELAX_RECETA_FITOSANIDAD_CATALOG_FKS_MIGRATION } from "./020-relax-receta-fitosanidad-catalog-fks";
import { VISITA_RIEGO_CONTEXT_FIELDS_MIGRATION } from "./021-visita-riego-context-fields";
import { CULTIVO_CODE_REQUIRED_MIGRATION } from "./022-cultivo-code-required";

export const DATABASE_MIGRATIONS = [
  TERRITORIAL_SECTORS_AND_PIURA_GEOGRAPHY_MIGRATION,
  ETAPAS_FENOLOGICAS_ORDER_AND_TYPE_MIGRATION,
  SUB_ETAPAS_MIGRATION,
  VISITA_SUB_ETAPA_AND_AREA_MIGRATION,
  UPDATE_CUAJADO_SUB_ETAPAS_MIGRATION,
  PLAGAS_ENFERMEDADES_SCIENTIFIC_NAME_MIGRATION,
  NIVELES_INCIDENCIA_SEVERIDAD_MIGRATION,
  PLAGAS_ENFERMEDADES_ETAPA_FENOLOGICA_MIGRATION,
  PLAGAS_ENFERMEDADES_ETAPAS_NIVELES_MIGRATION,
  VISITA_SANITARY_SEVERITY_AND_STEP_NOTES_MIGRATION,
  NUTRIENTES_DETALLE_NUTRIENTES_MIGRATION,
  OPERATIONAL_CATALOGS_MIGRATION,
  VISITA_RIEGO_LABORES_MIGRATION,
  VISITA_OBSERVACION_SANITARIA_ORGANOS_MIGRATION,
  UPDATE_VISITA_OBSERVACION_SANITARIA_ORGANOS_MIGRATION,
  UPDATE_VISITA_OBSERVACION_SANITARIA_ORGANOS_CURRENT_VALUES_MIGRATION,
  STANDARDIZE_STEP_FIVE_FIELD_WORK_CATALOG_MIGRATION,
  VISIT_INCIDENCE_AND_NUTRITION_ORGANS_MIGRATION,
  VISITA_RECETAS_MIGRATION,
  RELAX_RECETA_FITOSANIDAD_CATALOG_FKS_MIGRATION,
  VISITA_RIEGO_CONTEXT_FIELDS_MIGRATION,
  CULTIVO_CODE_REQUIRED_MIGRATION
] as const;
