export const SQL_SCHEMA = [
  `CREATE TABLE IF NOT EXISTS cultivos (
    id TEXT PRIMARY KEY NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS variedades (
    id TEXT PRIMARY KEY NOT NULL,
    cultivo_id TEXT NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (cultivo_id) REFERENCES cultivos(id)
  )`,
  `CREATE TABLE IF NOT EXISTS campanias (
    id TEXT PRIMARY KEY NOT NULL,
    cultivo_id TEXT NOT NULL,
    name TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT,
    description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (cultivo_id) REFERENCES cultivos(id)
  )`,
  `CREATE TABLE IF NOT EXISTS etapas_fenologicas (
    id TEXT PRIMARY KEY NOT NULL,
    cultivo_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    sort_order INTEGER,
    type TEXT NOT NULL DEFAULT 'Etapa',
    is_active INTEGER NOT NULL DEFAULT 1,
    CHECK(type IN ('Etapa', 'Labor')),
    FOREIGN KEY (cultivo_id) REFERENCES cultivos(id)
  )`,
  `CREATE TABLE IF NOT EXISTS sub_etapas (
    id TEXT PRIMARY KEY NOT NULL,
    etapa_fenologica_id TEXT NOT NULL,
    name TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    description TEXT,
    percentage TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (etapa_fenologica_id) REFERENCES etapas_fenologicas(id)
  )`,
  `CREATE TABLE IF NOT EXISTS pest_diseases (
    id TEXT PRIMARY KEY NOT NULL,
    scientific_name TEXT,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    is_active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS pest_disease_stage_levels (
    id TEXT PRIMARY KEY NOT NULL,
    pest_disease_id TEXT NOT NULL,
    phenological_stage_id TEXT NOT NULL,
    incidence_severity_level_id TEXT NOT NULL,
    description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (pest_disease_id) REFERENCES pest_diseases(id),
    FOREIGN KEY (phenological_stage_id) REFERENCES etapas_fenologicas(id),
    FOREIGN KEY (incidence_severity_level_id) REFERENCES incidence_levels(id)
  )`,
  `CREATE TABLE IF NOT EXISTS incidence_levels (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    type TEXT NOT NULL DEFAULT 'incidencia'
  )`,
  `CREATE TABLE IF NOT EXISTS nutrientes (
    id TEXT PRIMARY KEY NOT NULL,
    cultivo_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (cultivo_id) REFERENCES cultivos(id)
  )`,
  `CREATE TABLE IF NOT EXISTS detalle_nutrientes (
    id TEXT PRIMARY KEY NOT NULL,
    nutriente_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (nutriente_id) REFERENCES nutrientes(id)
  )`,
  `CREATE TABLE IF NOT EXISTS tipos_riego (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS labores_culturales (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    category_code TEXT,
    category_name TEXT,
    option_code TEXT,
    option_label TEXT,
    legend TEXT,
    sort_order INTEGER,
    is_active INTEGER NOT NULL DEFAULT 1
  )`,
  `CREATE TABLE IF NOT EXISTS productores (
    id TEXT PRIMARY KEY NOT NULL,
    public_id TEXT NOT NULL,
    entity_type TEXT NOT NULL DEFAULT 'persona',
    document_type_id INTEGER,
    document_number TEXT,
    first_name TEXT,
    last_name TEXT,
    phone TEXT,
    email TEXT,
    address TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS departamentos (
    id TEXT PRIMARY KEY NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS provincias (
    id TEXT PRIMARY KEY NOT NULL,
    departamento_id TEXT NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    FOREIGN KEY (departamento_id) REFERENCES departamentos(id)
  )`,
  `CREATE TABLE IF NOT EXISTS distritos (
    id TEXT PRIMARY KEY NOT NULL,
    provincia_id TEXT NOT NULL,
    ubigeo TEXT NOT NULL,
    name TEXT NOT NULL,
    FOREIGN KEY (provincia_id) REFERENCES provincias(id)
  )`,
  `CREATE TABLE IF NOT EXISTS sectores (
    id TEXT PRIMARY KEY NOT NULL,
    distrito_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (distrito_id) REFERENCES distritos(id)
  )`,
  `CREATE TABLE IF NOT EXISTS subsectores (
    id TEXT PRIMARY KEY NOT NULL,
    sector_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (sector_id) REFERENCES sectores(id)
  )`,
  `CREATE TABLE IF NOT EXISTS parcelas (
    id TEXT PRIMARY KEY NOT NULL,
    public_id TEXT NOT NULL,
    productor_id TEXT NOT NULL,
    subsector_id TEXT NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    area_hectares TEXT,
    description TEXT,
    reference_point TEXT,
    geometry TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (productor_id) REFERENCES productores(id),
    FOREIGN KEY (subsector_id) REFERENCES subsectores(id)
  )`,
  `CREATE TABLE IF NOT EXISTS visitas_campo (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    public_id TEXT,
    nro_ficha TEXT,
    crop_id TEXT NOT NULL,
    variety_id TEXT NOT NULL,
    parcela_id TEXT NOT NULL,
    campaign_id TEXT NOT NULL,
    agronomist_user_id TEXT NOT NULL,
    plants_count INTEGER,
    area_hectares TEXT,
    sowing_date TEXT,
    visit_date TEXT NOT NULL,
    start_visit_time TEXT NOT NULL,
    end_visit_time TEXT,
    phenological_stage_id TEXT,
    sub_etapa_id TEXT,
    sub_etapa_percentage TEXT,
    general_observation TEXT,
    agronomist_signature_name TEXT,
    producer_signature_name TEXT,
    visit_location TEXT,
    receta_anterior_json TEXT,
    synchronized_at TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (crop_id) REFERENCES cultivos(id),
    FOREIGN KEY (variety_id) REFERENCES variedades(id),
    FOREIGN KEY (parcela_id) REFERENCES parcelas(id),
    FOREIGN KEY (campaign_id) REFERENCES campanias(id),
    FOREIGN KEY (phenological_stage_id) REFERENCES etapas_fenologicas(id),
    FOREIGN KEY (sub_etapa_id) REFERENCES sub_etapas(id)
  )`,
  `CREATE TABLE IF NOT EXISTS visita_evaluaciones (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    visita_local_id TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    incidence_percentage TEXT,
    percentage TEXT,
    description TEXT NOT NULL,
    organos_afectados TEXT,
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (visita_local_id) REFERENCES visitas_campo(local_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS visita_observaciones_sanitarias (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    visita_local_id TEXT NOT NULL,
    pest_disease_id TEXT NOT NULL,
    incidence_level_id TEXT,
    severity_level_id TEXT,
    incidence_percentage TEXT,
    observation TEXT,
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (visita_local_id) REFERENCES visitas_campo(local_id) ON DELETE CASCADE,
    FOREIGN KEY (pest_disease_id) REFERENCES pest_diseases(id),
    FOREIGN KEY (incidence_level_id) REFERENCES incidence_levels(id),
    FOREIGN KEY (severity_level_id) REFERENCES incidence_levels(id)
  )`,
  `CREATE TABLE IF NOT EXISTS visita_observacion_sanitaria_organos (
    local_id TEXT PRIMARY KEY NOT NULL,
    visita_observacion_sanitaria_local_id TEXT NOT NULL,
    organo TEXT NOT NULL CHECK(organo IN ('tronco_rama', 'yema_apical', 'brote_vegetativo', 'hoja_tierna', 'hoja_madura', 'panicula_floral', 'flor_individual', 'fruto_recien_cuajado', 'fruto_verde', 'fruto_maduro', 'raices')),
    created_at TEXT NOT NULL,
    FOREIGN KEY (visita_observacion_sanitaria_local_id) REFERENCES visita_observaciones_sanitarias(local_id) ON DELETE CASCADE,
    UNIQUE (visita_observacion_sanitaria_local_id, organo)
  )`,
  `CREATE TABLE IF NOT EXISTS visita_paso_observaciones (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    visita_local_id TEXT NOT NULL,
    step_number INTEGER NOT NULL,
    observation TEXT,
    recommendation TEXT,
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    sync_error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (visita_local_id) REFERENCES visitas_campo(local_id) ON DELETE CASCADE,
    UNIQUE (visita_local_id, step_number)
  )`,
  `CREATE TABLE IF NOT EXISTS visita_riegos (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    visita_local_id TEXT NOT NULL,
    tipo_riego_id TEXT NOT NULL,
    fuente_agua TEXT DEFAULT NULL CHECK(fuente_agua IS NULL OR fuente_agua IN ('subterranea', 'superficial', 'pluvial')),
    tipo_suelo TEXT DEFAULT NULL CHECK(tipo_suelo IS NULL OR tipo_suelo IN ('arenoso', 'arcilloso', 'limoso', 'franco')),
    humedad_suelo TEXT DEFAULT NULL CHECK(humedad_suelo IS NULL OR humedad_suelo IN ('saturado', 'optimo', 'moderadamente_seco', 'seco')),
    estres_hidrico INTEGER DEFAULT NULL CHECK(estres_hidrico IS NULL OR estres_hidrico IN (0, 1)),
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    sync_error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (visita_local_id) REFERENCES visitas_campo(local_id) ON DELETE CASCADE,
    FOREIGN KEY (tipo_riego_id) REFERENCES tipos_riego(id),
    UNIQUE (visita_local_id)
  )`,
  `CREATE TABLE IF NOT EXISTS visita_labores_culturales (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    visita_local_id TEXT NOT NULL,
    labor_cultural_id TEXT NOT NULL,
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    sync_error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (visita_local_id) REFERENCES visitas_campo(local_id) ON DELETE CASCADE,
    FOREIGN KEY (labor_cultural_id) REFERENCES labores_culturales(id),
    UNIQUE (visita_local_id, labor_cultural_id)
  )`,
  `CREATE TABLE IF NOT EXISTS coadyuvantes (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    description TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS ingredientes_activos (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    description TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS marcas_producto (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    tipo_producto_id TEXT,
    ingrediente_activo_id TEXT,
    concentracion TEXT,
    ingrediente_activo_nombre TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS modos_accion (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS tipos_control (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS tipos_producto_fitosanitario (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS fertilizantes (
    id TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('solido', 'liquido'))
  )`,
  `CREATE TABLE IF NOT EXISTS visita_recetas (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    visita_local_id TEXT NOT NULL,
    etapa_fenologica TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    sync_error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (visita_local_id) REFERENCES visitas_campo(local_id) ON DELETE CASCADE,
    UNIQUE (visita_local_id)
  )`,
  `CREATE TABLE IF NOT EXISTS visita_receta_fitosanidad (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    receta_local_id TEXT NOT NULL,
    numero INTEGER NOT NULL DEFAULT 1,
    objetivo TEXT NOT NULL CHECK(objetivo IN ('plaga', 'enfermedad')),
    objetivo_nombre TEXT NOT NULL,
    tipo_control_id TEXT,
    tipo_producto_id TEXT,
    disolvente TEXT NOT NULL DEFAULT 'Agua',
    modo_accion_id TEXT,
    ingrediente_activo_nombre TEXT,
    dosis_ia TEXT,
    volumen_aplicacion TEXT,
    cantidad_total_ia TEXT,
    marca_producto_nombre TEXT,
    concentracion_producto TEXT,
    cantidad_total_producto TEXT,
    coadyuvantes_ids TEXT,
    orden_mezcla TEXT,
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (receta_local_id) REFERENCES visita_recetas(local_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS visita_receta_fertilizacion (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    receta_local_id TEXT NOT NULL,
    via_aplicacion TEXT NOT NULL CHECK(via_aplicacion IN ('edafica', 'foliar')),
    fertilizante_nombre TEXT,
    tipo_producto TEXT CHECK(tipo_producto IN ('solido', 'liquido')),
    dosis TEXT,
    unidad_dosis TEXT,
    cantidad_total_plantas TEXT,
    volumen_aplicacion TEXT,
    cantidad_total_fertilizante TEXT,
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (receta_local_id) REFERENCES visita_recetas(local_id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS visita_receta_riego (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    receta_local_id TEXT NOT NULL,
    tipo_recomendacion TEXT NOT NULL CHECK(tipo_recomendacion IN ('riego_pesado', 'riego_ligero', 'inicio_agoste', 'ruptura_agoste')),
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (receta_local_id) REFERENCES visita_recetas(local_id) ON DELETE CASCADE,
    UNIQUE (receta_local_id)
  )`,
  `CREATE TABLE IF NOT EXISTS visita_receta_labores (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    receta_local_id TEXT NOT NULL,
    labor TEXT NOT NULL CHECK(labor IN ('limpieza_maleza_pala', 'limpieza_maleza_motoguadana', 'horqueteo', 'enzunchado', 'recoleccion_frutos', 'trampas_mosca')),
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (receta_local_id) REFERENCES visita_recetas(local_id) ON DELETE CASCADE,
    UNIQUE (receta_local_id, labor)
  )`,
  `CREATE TABLE IF NOT EXISTS visita_calificaciones (
    local_id TEXT PRIMARY KEY NOT NULL,
    server_id TEXT,
    visita_local_id TEXT NOT NULL,
    modulo TEXT NOT NULL CHECK(modulo IN ('plagas','enfermedades','nutricion','riego','labores')),
    puntaje INTEGER NOT NULL CHECK(puntaje >= 0 AND puntaje <= 3),
    observacion TEXT,
    justificado INTEGER,
    categoria_justificacion TEXT,
    motivo_justificacion TEXT,
    sync_status TEXT NOT NULL DEFAULT 'pending' CHECK(sync_status IN ('pending', 'synced', 'error')),
    sync_error_message TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (visita_local_id) REFERENCES visitas_campo(local_id) ON DELETE CASCADE,
    UNIQUE (visita_local_id, modulo)
  )`,
  `CREATE TABLE IF NOT EXISTS app_meta (
    key TEXT PRIMARY KEY NOT NULL,
    value TEXT
  )`,
  `CREATE TABLE IF NOT EXISTS sync_state (
    id TEXT PRIMARY KEY NOT NULL,
    window_json TEXT NOT NULL DEFAULT '[]',
    consecutive_failures INTEGER NOT NULL DEFAULT 0,
    consecutive_successes INTEGER NOT NULL DEFAULT 0,
    backoff_step INTEGER NOT NULL DEFAULT 0,
    last_attempt_at TEXT,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS sync_failures (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_type TEXT NOT NULL,
    entity_local_id TEXT NOT NULL,
    operation TEXT NOT NULL CHECK(operation IN ('create', 'update', 'delete')),
    payload TEXT,
    retry_count INTEGER NOT NULL DEFAULT 0 CHECK(retry_count >= 0),
    error_kind TEXT NOT NULL CHECK(error_kind IN ('transient', 'permanent')),
    error_message TEXT,
    outbox_created_at TEXT NOT NULL,
    last_attempt_at TEXT NOT NULL,
    failed_at TEXT NOT NULL,
    UNIQUE(entity_type, entity_local_id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_sync_failures_kind_failed_at
    ON sync_failures(error_kind, failed_at)`
] as const;
